name: diary_app
description: A simple and efficient diary app for daily reflections
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  path_provider: ^2.1.5
  
  # JSON Handling
  json_annotation: ^4.8.1
  
  # Date Utils
  intl: ^0.20.2
  
  # UI Components
  table_calendar: ^3.0.9
  
  # File operations
  file_selector: ^1.0.3
  share_plus: ^7.2.2
  permission_handler: ^12.0.1
  
  # Calendar integration - 필요 시 활성화 가능
  # device_calendar: ^4.3.1
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # Home Screen Widget
  home_widget: ^0.7.0
  
  # SharedPreferences (위젯 데이터 공유용)
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
